### ISSUE TITLE
IllegalArgumentException when breaking a Fruit Press 

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.11#59]
When you break the Fruit Press, it destroys both blocks but spawns another block that appears to not be registered.

`[12:01:07] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:801) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:699) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=pressed, clazz=class growthcraft.cellar.common.block.BlockFruitPresser$PressState, values=[UNPRESSED, PRESSED]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:204) ~[BlockStateContainer$StateImplementation.class:?]
	at growthcraft.cellar.common.tileentity.device.FruitPress.isPressed(FruitPress.java:44) ~[FruitPress.class:?]
	at growthcraft.cellar.common.tileentity.device.FruitPress.preparePressing(FruitPress.java:53) ~[FruitPress.class:?]
	at growthcraft.cellar.common.tileentity.device.FruitPress.update(FruitPress.java:97) ~[FruitPress.class:?]
	at growthcraft.cellar.common.tileentity.TileEntityFruitPress.update(TileEntityFruitPress.java:86) ~[TileEntityFruitPress.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1961) ~[World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:651) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:795) ~[MinecraftServer.class:?]
	... 4 more
[12:01:07] [Server thread/ERROR]: This crash report has been saved to: G:\Projects\Forge\Avatair\Growthcraft-1.11\run\.\crash-reports\crash-2018-01-17_12.01.07-server.txt
[12:01:07] [Server thread/INFO]: Stopping server
[12:01:07] [Server thread/INFO]: Saving players
[12:01:07] [Server thread/INFO]: Saving worlds
[12:01:07] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[12:01:07] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:600]: ---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 1/17/18 12:01 PM
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=pressed, clazz=class growthcraft.cellar.common.block.BlockFruitPresser$PressState, values=[UNPRESSED, PRESSED]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:204)
	at growthcraft.cellar.common.tileentity.device.FruitPress.isPressed(FruitPress.java:44)
	at growthcraft.cellar.common.tileentity.device.FruitPress.preparePressing(FruitPress.java:53)
	at growthcraft.cellar.common.tileentity.device.FruitPress.update(FruitPress.java:97)
	at growthcraft.cellar.common.tileentity.TileEntityFruitPress.update(TileEntityFruitPress.java:86)
	at net.minecraft.world.World.updateEntities(World.java:1961)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:651)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:795)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:699)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:204)
	at growthcraft.cellar.common.tileentity.device.FruitPress.isPressed(FruitPress.java:44)
	at growthcraft.cellar.common.tileentity.device.FruitPress.preparePressing(FruitPress.java:53)
	at growthcraft.cellar.common.tileentity.device.FruitPress.update(FruitPress.java:97)
	at growthcraft.cellar.common.tileentity.TileEntityFruitPress.update(TileEntityFruitPress.java:86)

-- Block entity being ticked --
Details:
	Name: growthcraft_cellar:fruit_press // growthcraft.cellar.common.tileentity.TileEntityFruitPress
	Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (89,76,262), Chunk: (at 9,4,6 in 5,16; contains blocks 80,0,256 to 95,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1961)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:651)`

**Comment by Avatair** [comment]
Was fixed.
